### ISSUE TITLE
Its this still working

### ISSUE THREAD

**Issue by crack00r** [luisramirez-m/warzone-discord-bot#6]
i just get a crash at start

2022-02-09T23:32:12.241893+00:00 heroku[web.1]: Stopping process with SIGKILL
2022-02-09T23:32:12.406786+00:00 heroku[web.1]: Process exited with status 137
2022-02-09T23:32:12.489321+00:00 heroku[web.1]: State changed from starting to crashed
2022-02-09T23:32:12.545094+00:00 heroku[web.1]: State changed from crashed to starting
2022-02-09T23:32:14.630299+00:00 heroku[web.1]: Starting process with command `npm start`
2022-02-09T23:32:16.227055+00:00 app[web.1]: 
2022-02-09T23:32:16.227070+00:00 app[web.1]: > warzone-discord-bot@1.0.0 start
2022-02-09T23:32:16.227070+00:00 app[web.1]: > node --trace-warnings ./src/index.js
2022-02-09T23:32:16.227070+00:00 app[web.1]: 
2022-02-09T23:32:17.003046+00:00 app[web.1]: Ready!

**Comment by luisramirezdev** [comment]
I think is a problem from heroku, because app is ready. You can run on local for test it ?

**Comment by crack00r** [comment]
Is it maybe possible to add aHowTo for Selfhosting?
I have a root with Ubuntu 18, but no clue a how to install it :/

**Comment by crack00r** [comment]
![image](https://user-images.githubusercontent.com/6163329/153570491-7c59e856-fe82-4287-b1ff-950dbf3fee8d.png)

**Comment by crack00r** [comment]
![image](https://user-images.githubusercontent.com/6163329/153570592-74deea15-32ec-4197-a080-4bcdd2a6fc25.png)

**Comment by crack00r** [comment]
![image](https://user-images.githubusercontent.com/6163329/153571279-1bad35b2-fa6d-4214-8f2f-675ed7068d60.png)

**Comment by luisramirezdev** [comment]
Mmm..

1. Your server linux need to have `node` and `npm`.
2. After install `node` and `npm`, you need to clone the repository
3. You need to install all dependencies from npm, these actions are with the command `npm install` (check you are on the folder from the repository).
4. And use `npm run start` to start the bot.

Is a fast how to, I hope you can make it.

**Comment by crack00r** [comment]
already have it install, but didnt help :/

![image](https://user-images.githubusercontent.com/6163329/153574355-838dcb34-4519-4ee7-9dde-8713280f7b38.png)

**Comment by luisramirezdev** [comment]
After that you need to do the step 3

**Comment by crack00r** [comment]
![image](https://user-images.githubusercontent.com/6163329/153579902-1c1ba98d-e69d-4642-9952-a2cb492c3600.png)

**Comment by crack00r** [comment]
any help on this, login is 100% correct

**Comment by luisramirezdev** [comment]
Maybe the `call-of-duty-api` package is out of date, i will try this weekend to see if it's working.

**Comment by crack00r** [comment]
n1, thx!

**Comment by luisramirezdev** [comment]
Hey in this discord bot I use this package https://docs.codapi.dev/ to get Call of duty data, but Call of duty change the login to get data. The problem is you need to pass captcha's and you need to pay to generate always captcha's something like 2captcha.com.

Unfortunately I no longer have the time and dedication to update the discord bot.

You can use my code for adapting it with the new Call of duty package and login changes
